### ISSUE TITLE
Github actions

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#240]
By adding a file `.github/workflows/test.yml` with this content

```yaml
name: Run all D Tests
on: [push, pull_request]

jobs:
    test:
        name: Dub Tests
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
                dc: [dmd-latest, ldc-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1

            - name: Install D compiler
              uses: mihails-strasuns/setup-dlang@v0.3.0
              with:
                  compiler: ${{ matrix.dc }}

            - name: Run tests
              run: dub test -b syntax
```

there will be a pull request voter, checking the syntax of the dub sub packages specified here
https://github.com/adamdruppe/arsd/blob/master/dub.json#L9

The syntax is checked on windows, linux and macos.
(One thing is missing, it only test x86_64 architecture, as this is now Dub default for all OS)

It only checks the syntax because the sub packages might have additional system dependencies which causes linker failures.
